### PR TITLE
consolidated parameters in init/probe/de-init, in preparation

### PR DESCRIPTION
**Pull request by xxandy**
for integration with higher layers on spring-8 side.

Note that this has no functional changes.
All changes are consolidating API parameters, to make it easier to integrate with spring8 upper layer s/w.

### CODE REVIEW

**Comment by ludwigpetrosyan** [comment]
it is OK, but I think we have to keep the function interface to be capable with the existing drivers,
we could do it some how using default arguments, and in the function check which one is defined

 struct file_operations _pciedev_fops, pciedev_cdev *pciedev_cdev_p, char *dev_name = NULL, int \* brd_num = NULL)
struct file_operations *pciedev_fops, pciedev_cdev *pciedev_cdev_p, pciedev_dev *_ ppnew_device= NULL )

if(dev_name){
.....
}else{
....
}

**Comment by ludwigpetrosyan** [comment]
sorry I mean:
struct file_operations pciedev_fops, pciedev_cdev *pciedev_cdev_p, pciedev_dev \* ppnew_device= NULL, char *dev_name = NULL, int \* brd_num = NULL)

if(dev_name){
.....
}else{
....
}

**Comment by xxandy** [comment]
I understand, it makes sense to keep backwards compatibility.
Since this is C language (not C++) ,  default arguments are not an option.
However, I can preserve the previous function name and create a different function with the new arguments.

**Comment by xxandy** [comment]
With these changes, the compatibility with previous versions is restored.
Furthermore, the #ifdef tests for different linux versions move to the universal driver header, which makes it so that individual drivers have cleaner, more maintanable code.

**Pull request closed without merging**
